# app/config/config.yml

liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~

        caroussel :

            quality : 75

            filters :

                thumbnail  : { size : [480, 200], mode : outbound }
                background : { size : [485, 210], position : center, color : '#000000' }
        profile:

            quality: 75

            filters:

                thumbnail: { size: [ 25, 25 ], mode: outbond }

